name:                stargaze-cli
version:             0.1.0.0
github:              "nodew/stargaze-cli"
license:             BSD3
author:              "Qiao Wang"
maintainer:          "wangqiao11@hotmail.com"
copyright:           "2022 Qiao Wang"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/nodew/stargaze-cli#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- aeson-pretty
- bytestring
- req
- path
- path-io
- text
- time

library:
  source-dirs: src

executables:
  stargaze:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stargaze-cli

tests:
  stargaze-cli-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - stargaze-cli
